"""
小红书 XHS 视频提取器（yt-dlp 方式）

原理：
1. 将 Cookie 字符串转为 Netscape 格式临时文件（yt-dlp 要求此格式）
2. 调用 yt-dlp 提取视频信息（不下载，仅获取 URL）
3. yt-dlp 内部自动处理 XHS 的加密签名、xsec_token 等

相比直接 HTML 解析的优势：
- yt-dlp 维护了 XHS 的签名算法（浏览器 JS 执行）
- 处理 xsec_token、加密参数等反爬机制
- 自动处理 Cookie 会话 + xsec_token 会话不一致问题
"""

import os
import re
import json
import tempfile
import subprocess
import sys
from .tikhub_client import extract_xiaohongshu_note_id


# yt-dlp 在 venv 中
_YTDLP = os.path.join(
    os.path.dirname(sys.executable), "yt-dlp.exe"
)


def _cookie_str_to_netscape(cookie_str: str) -> str:
    """
    将 'key=val; key2=val2' 格式转为 Netscape cookie file 格式。
    XHS 关键字段：a1, web_session, webId, websectiga, xsecappid, sec_poison_id
    """
    lines = [
        "# Netscape HTTP Cookie File",
        "# This file was generated by douyin_subtitle_project",
        ".xiaohongshu.com\tTRUE\t/\tFALSE\t0\txsecappid\txhs-pc-web",
    ]
    for part in cookie_str.split(";"):
        part = part.strip()
        if not part or "=" not in part:
            continue
        key, _, value = part.partition("=")
        key = key.strip()
        value = value.strip()
        if not key:
            continue
        # 跳过空值
        if not value:
            continue
        # 特殊处理带 = 的 value（base64 encoded tokens）
        # 已经 partition 过所以这里 value 里不含 = 号
        lines.append(
            f".xiaohongshu.com\tTRUE\t/\tFALSE\t0\t{key}\t{value}"
        )
    return "\n".join(lines)


def fetch_xhs_note_info(url: str, cookie: str) -> dict:
    """
    用 yt-dlp 提取小红书笔记信息（支持视频笔记）。

    返回格式:
        success=True:  {"success": True,  "note_id": "...", "title": "...",
                        "desc": "...", "video_url": "...", "type": "video"|"normal"}
        success=False: {"success": False, "error": "..."}
    """
    note_id = extract_xiaohongshu_note_id(url)
    if not note_id:
        return {"success": False, "error": f"无法从 URL 提取 note_id: {url}"}

    # 生成 Netscape 格式 Cookie 文件
    netscape_content = _cookie_str_to_netscape(cookie)

    cookie_file = None
    try:
        fd, cookie_file = tempfile.mkstemp(suffix=".txt", prefix="xhs_cookies_")
        # mkstemp 返回已打开的 fd，写入内容
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            f.write(netscape_content)

        # yt-dlp 命令：只获取 info，不下载
        cmd = [
            _YTDLP,
            "--cookies", cookie_file,
            "--dump-json",
            "--no-download",
            "--no-warnings",
            "--quiet",
            url,
        ]

        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=60,
            encoding="utf-8",
            errors="replace",
        )

        if result.returncode != 0:
            stderr = result.stderr.strip()
            if not stderr:
                stderr = result.stdout.strip()
            return {
                "success": False,
                "error": f"yt-dlp 提取失败: {stderr or '未知错误'}",
            }

        try:
            info = json.loads(result.stdout.strip().split("\n")[-1])
        except json.JSONDecodeError:
            return {
                "success": False,
                "error": f"yt-dlp 返回格式异常: {result.stdout[:200]}",
            }

        # yt-dlp 返回值解析
        # XHS 视频：formats[0].url 里有完整流地址
        # 纯图文：无 formats 或 formats 为空
        formats = info.get("formats") or []
        video_url = ""
        if formats and isinstance(formats, list):
            # 取第一个格式（通常最高质量）
            video_url = formats[0].get("url", "") or ""

        title = info.get("title", "") or ""
        uploader = info.get("uploader", "") or ""
        description = info.get("description", "") or ""

        if not video_url:
            # 纯图文笔记（无视频）
            return {
                "success": True,
                "note_id": note_id,
                "title": title,
                "desc": description,
                "video_url": None,
                "images": [],
                "type": "normal",
            }

        return {
            "success": True,
            "note_id": note_id,
            "title": title,
            "desc": description,
            "video_url": video_url,
            "images": [],
            "type": "video",
            "uploader": uploader,
        }

    except subprocess.TimeoutExpired:
        return {"success": False, "error": "yt-dlp 提取超时（60s），网络可能较慢"}
    except Exception as e:
        return {"success": False, "error": f"提取异常: {e}"}
    finally:
        if cookie_file and os.path.exists(cookie_file):
            try:
                os.unlink(cookie_file)
            except OSError:
                pass
